### ISSUE TITLE
"&" does not display correctly in the filters

### ISSUE THREAD

**Issue by MonikaBarget** [Maynooth-Center-for-Digital-Humanities/letters-ui#6]
e.g. "Blake &amp; Kenny Solicitors (1)" in the filter is not displayed correctly. Where and when should this issue be fixed? Can Padraig do some Python programming to sort this out automatically.

**Comment by stavrosangelis** [comment]
This results from the data in the XML file. When the data team decides on the encoding of special characters and the data cleaning process is performed this information will appear correctly.
