### ISSUE TITLE
Discuss advantages of a permanent link

### ISSUE THREAD

**Issue by MonikaBarget** [Maynooth-Center-for-Digital-Humanities/letters-ui#9]
Many online databases offer permanent links for their items as researchers might want to quote individual web pages in their publications. How could a permanent link for a letter look like if we still which to display version updates? This issue relates to the necessity of displaying initial XML IDs at least temporarily to make data manual corrections possible.

**Comment by stavrosangelis** [comment]
As discussed we do not have a permanent URL resolver and the library cannot provide DOIs. Also if the domain changes the current URLs will become obsolete. 

To expose initial XML IDs a new endpoint has been created : {domain}/letter/{XMLID}. This endpoint always serves the latest version of an xml file.
